eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.207:8761/eureka/
      
server:
  port: 8764
  
spring:
  application:
    name: eshop-inventory-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.1.205:3306/eshop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root